This method is to efficiently find the accuracy of the different models.

The entire dataset is splited into k folds, 1st time 1st fold is made to test set and remaining is training set and evaluated,...., last fold is test and remaining is traininng set and evaluated and based on this differnet models are evaluated and we'll find the best

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [17]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\syamp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [19]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9833333333333333

In [23]:
RF = RandomForestClassifier()
RF.fit(x_train,y_train)
RF.score(x_test,y_test)

0.9648148148148148

Everytime we execute the accuracy changes, that why we use KFold Cross Validation

In [26]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

Example

In [29]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Function to find score

In [32]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test,y_test)

In [34]:
get_score(svm, x_train, x_test, y_train, y_test)

0.9833333333333333

3 April 2025 12:30 PM

# Stratified KFold
Stratified KFold takes two inputs array of features and array of labels

Example, x=[1,2,3,4,5,6,7,8,9], y=[1,1,1,2,2,2,3,3,3]

It makes sure each fold has equal distribution of each class, wheras KFold randomly does that without.

Example output for k=3, [1,4,7], [2,5,8], [3,6,9]

# Enumerate

Normally, when iterating over a list, you use:
items = ["apple", "banana", "cherry"]
for item in items:
    print(item)

But if you also need the index, you usually do:
for i in range(len(items)):
    print(i, items[i])

Instead of this, enumerate() simplifies it:
for i, item in enumerate(items):
    print(i, item)

In [36]:
#Example
from sklearn.model_selection import StratifiedKFold
import numpy as np

# Sample Data (features and corresponding labels)
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])  # Labels (3 classes)

# Initialize Stratified K-Fold with 3 splits
folds = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# Splitting the dataset
for fold, (train_idx, test_idx) in enumerate(folds.split(X, y)):
    print(f"Fold {fold+1}")
    print("Train indices:", train_idx, "Test indices:", test_idx)
    print()

Fold 1
Train indices: [1 2 3 4 7 8] Test indices: [0 5 6]

Fold 2
Train indices: [0 2 4 5 6 8] Test indices: [1 3 7]

Fold 3
Train indices: [0 1 3 5 6 7] Test indices: [2 4 8]



# Creating Folds

In [64]:
from sklearn.model_selection import StratifiedKFold # similar to KFold but it does the work even better coz it splits the data uniformly
folds = KFold(n_splits=3)

In [66]:
for fold, (train_idx, test_idx) in enumerate(folds.split(digits.data, digits.target)):
    print(f"Fold {fold+1}")
    print("Train indices:", train_idx[:10], '....')
    print("Test indices:", test_idx[:10], '....')
    print()
    

Fold 1
Train indices: [599 600 601 602 603 604 605 606 607 608] ....
Test indices: [0 1 2 3 4 5 6 7 8 9] ....

Fold 2
Train indices: [0 1 2 3 4 5 6 7 8 9] ....
Test indices: [599 600 601 602 603 604 605 606 607 608] ....

Fold 3
Train indices: [0 1 2 3 4 5 6 7 8 9] ....
Test indices: [1198 1199 1200 1201 1202 1203 1204 1205 1206 1207] ....



# Spliting Data & Evaluation Accuracy

In [104]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_idx, test_idx in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_idx], digits.data[test_idx], digits.target[train_idx], digits.target[test_idx]

    scores_lr.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=100), x_train, x_test, y_train, y_test))

C:\Users\syamp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\syamp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [105]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [106]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [107]:
scores_rf

[0.9415692821368948, 0.9449081803005008, 0.9215358931552587]

# Evaluating different models using sklearn library

In [113]:
from sklearn.model_selection import cross_val_score # this internally creates folds, test and predict score for different score

In [119]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\syamp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\syamp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [121]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [123]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.94166667, 0.91388889, 0.95264624, 0.96657382, 0.93314763])